## https://dev.to/jameswallis/using-github-composite-actions-to-make-your-workflows-smaller-and-more-reusable-476l
name: "Checkout and install"

inputs:
  npm_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup npm token
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ inputs.npm_token }}
      shell: bash

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6
        run_install: |
          - args: [--frozen-lockfile]
